//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseSchedule()
        {
            this.RegisteredCourses = new HashSet<RegisteredCours>();
        }
    
        public int Course_ID { get; set; }
        public string Course_Title { get; set; }
        public string Description { get; set; }
        public string Language { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Start_Time { get; set; }
        public System.DateTime End_Time { get; set; }
        public string Course_Status { get; set; }
        public int Seats_Number { get; set; }
        public string Course_Place { get; set; }
        public string User_Type { get; set; }
        public int Classification_ID { get; set; }
        public string Course_Type { get; set; }
        public int Certificate_ID { get; set; }
        public string Trainer_Name { get; set; }
    
        public virtual CertificateTemplate CertificateTemplate { get; set; }
        public virtual CourseClassification CourseClassification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisteredCours> RegisteredCourses { get; set; }
    }
}
